/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'felipe' at '2/1/17 11:40 AM' with Gradle 2.10
 *
 * @author felipe, @date 2/1/17 11:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
